out.x: test_automaton.o cellularautomaton.o
	g++ -o out.x test_automaton.o cellularautomaton.o

test_automaton.o: test_automaton.cpp
	g++ -c test_automaton.cpp -std=c++1y

cellularautomaton.o: cellularautomaton.cpp
	g++ -c cellularautomaton.cpp -std=c++1y